config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'homes#top'
  get '/about' => 'homes#about', as: 'about'
  post "/homes/guest_sign_in", to: "homes#new_guest"
  resources :posts do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
  end
  get "users/withdraw/:id" => "users#withdraw", as: "users_withdraw"
  resources :chats, only: [:create]
  get "chat/:id" => "chats#show", as: "chat"
  resources :notifications, only: [:index]
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  validates :user_id, presence: true, uniqueness: { scope: :post_id }
  validates :post_id, presence: true
  belongs_to :user
  belongs_to :post
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    favorites = @post.favorites.new(user_id: current_user.id)
    favorites.save
    @post.create_notification_favorite!(current_user)
    @favorites = Favorite.where(post_id: params[:post_id])
  end

  def destroy
    @post = Post.find(params[:post_id])
    favorites = @post.favorites.find_by(user_id: current_user.id)
    favorites.destroy
    @favorites = Favorite.where(post_id: params[:post_id])
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite-btn.html.erb
<% if user_signed_in? %>
  <% if post.favorited_by?(current_user) %>
    <%= link_to post_favorites_path(post), class: "favorite-btn", method: :delete, remote: true do %>
      <i class="fas fa-thumbs-up"></i><%= post.favorites.count %>いいね
    <% end %>
  <% else %>
    <%= link_to post_favorites_path(post), class: "favorite-btn", method: :post, remote: true do %>
      <i class="far fa-thumbs-up"></i><%= post.favorites.count %>いいね
    <% end %>
  <% end %>
<% else %>
  <i class="fas fa-thumbs-up"></i><%= post.favorites.count %>いいね
<% end %>

app/views/favorites/_favorite-users.html.erb
<% favorites.each do |favorite| %>
  <tbody>
    <td><%= attachment_image_tag favorite.user, :profile_image, size: "50x50", format: 'jpeg', fallback: "no_image.jpg", class: "rounded-circle" %></td>
    <% if user_signed_in? %>
      <td class="pl-3"><%= link_to favorite.user.name, user_path(favorite.user) %></td>
    <% else %>
      <td class="pl-3"><%= favorite.user.name %></td>
    <% end %>
  </tbody>
<% end %>

app/views/favorites/_favorites.html.erb
<% if post.favorited_by?(current_user) %>
  <p>
    <%= link_to post_favorites_path(post), method: :delete do %>
      <i class="fas fa-thumbs-up"></i><%= post.favorites.count %>いいね
    <% end %>
  </p>
<% else %>
  <p>
    <%= link_to post_favorites_path(post), method: :post do %>
      <i class="far fa-thumbs-up"></i><%= post.favorites.count %>いいね
    <% end %>
  </p>
<% end %>

app/views/favorites/create.js.erb
$("#like-box").html("<%= j(render 'favorites/favorite-btn', post: @post) %>");
$("#favorite-users").html("<%= j(render "favorites/favorite-users", favorites: @favorites) %>");

app/views/favorites/destroy.js.erb
$("#like-box").html("<%= j(render 'favorites/favorite-btn', post: @post) %>");
$("#favorite-users").html("<%= j(render "favorites/favorite-users", favorites: @favorites) %>");