config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'homes#top'
  get '/about' => 'homes#about', as: 'about'
  post "/homes/guest_sign_in", to: "homes#new_guest"
  resources :posts do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
  end
  get "users/withdraw/:id" => "users#withdraw", as: "users_withdraw"
  resources :chats, only: [:create]
  get "chat/:id" => "chats#show", as: "chat"
  resources :notifications, only: [:index]
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    current_user.follow(params[:user_id])
    @user = User.find(params[:user_id])
    @user.create_notification_follow!(current_user)
  end

  def destroy
    current_user.unfollow(params[:user_id])
    @user = User.find(params[:user_id])
  end

  def followings # フォロー一覧
    @user = User.find(params[:user_id])
    @users = @user.followings.order(created_at: :desc).page(params[:page]).per(10)
  end

  def followers # フォロワー一覧
    @user = User.find(params[:user_id])
    @users = @user.followers.order(created_at: :desc).page(params[:page]).per(10)
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow_button.html.erb
<% if current_user.following?(user) %>
   <%= link_to "フォロー中", user_relationships_path(user.id), remote: true, method: :delete, class: "btn btn-primary btn-sm" %>
<% else %>
   <%= link_to "フォローする", user_relationships_path(user.id), remote: true, method: :post, class: "btn btn-info btn-sm" %>
<% end %>

app/views/relationships/_follow_count_follower.html.erb
<%= link_to user.followers.count, user_followers_path(user), class: "align-middle" %>

app/views/relationships/_follow_count_following.html.erb
<%= link_to user.followings.count, user_followings_path(user), class: "align-middle" %>

app/views/relationships/create.js.erb
$("#follow-button").html("<%= j(render "relationships/follow_button", user: @user) %>");
$("#followings-count").html("<%= j(render "relationships/follow_count_following", user: @user) %>");
$("#followers-count").html("<%= j(render "relationships/follow_count_follower", user: @user) %>");
$("#chat-button").html("<%= j(render "chats/chat_button", user: @user) %>");

app/views/relationships/destroy.js.erb
$("#follow-button").html("<%= j(render "relationships/follow_button", user: @user) %>");
$("#followings-count").html("<%= j(render "relationships/follow_count_following", user: @user) %>");
$("#followers-count").html("<%= j(render "relationships/follow_count_follower", user: @user) %>");
$("#chat-button").html("<%= j(render "chats/chat_button", user: @user) %>");

app/views/relationships/followers.html.erb
<div class="contianer">
  <% if current_user == @user %>
    <h2 class="text-center p-3">フォロワー</h2>
  <% else %>
    <h2 class="text-center p-3"><%= @user.name %>さんのフォロワー</h2>
  <% end %>
  <% if @users.exists? %>
    <%= render "users/index", users: @users %>
  <% else %>
    <p class="text-center">フォロワーユーザーはいません</p>
  <% end %>
</div>

app/views/relationships/followings.html.erb
<div class="contianer">
  <% if current_user == @user %>
    <h2 class="text-center p-3">フォロー中</h2>
   <% else %>
    <h2 class="text-center p-3"><%= @user.name %>さんがフォロー中</h2>
  <% end %>
  <% if @users.exists? %>
    <%= render "users/index", users: @users %>
  <% else %>
    <p class="text-center">フォローしているユーザーはいません</p>
  <% end %>
</div>