config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'homes#top'
  get '/about' => 'homes#about', as: 'about'
  post "/homes/guest_sign_in", to: "homes#new_guest"
  resources :posts do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
  end
  get "users/withdraw/:id" => "users#withdraw", as: "users_withdraw"
  resources :chats, only: [:create]
  get "chat/:id" => "chats#show", as: "chat"
  resources :notifications, only: [:index]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true, uniqueness: true, length: { maximum: 20 }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship",
                                      foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, class_name: "Relationship",
                           foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :user_rooms, dependent: :destroy
  has_many :chats
  has_many :active_notifications, class_name: "Notification",
                                  foreign_key: "visiter_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification",
                                   foreign_key: "visited_id", dependent: :destroy
  has_many :login_histories, dependent: :destroy
  attachment :profile_image

 
  validates :introduction, length: { maximum: 100 }

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  # フォローされた時の通知
  def create_notification_follow!(current_user)
    temp = current_user.active_notifications.where(visited_id: id, action: "follow")
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id, action: "follow"
      )
      notification.save if notification.valid?
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @users = User.all.order(created_at: :desc).page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.all.order(created_at: :desc).page(params[:page]).per(5)
  end

  def edit
    @user = User.find(params[:id])
    if @user.email == "guest@example.com"
      redirect_to user_path(@user), notice: "ゲストユーザーは編集できません"
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "更新できました"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.email == "guest@example.com"
      redirect_to user_path(@user), notice: "ゲストユーザーは削除できません"
    else
      @user.destroy
      flash[:notice] = "ユーザーを削除しました"
      redirect_to root_path
    end
  end

  def withdraw # 退会
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<div class="row mb-4">
  <table class="table table-borderless table-hover">
  <thead class="table-info">
    <tr class="text-center">
      <th scope="col-md-3">プロフィール画像</th>
      <th scope="col-md-3">名前</th>
      <th scope="col-md-4">プロフィール</th>
      <th scope="col-md-2">投稿数</th>
    </tr>
  </thead>
 <% users.each do |user| %>
      <tbody>
        <tr class="text-center">
          <th scope="row">
            <%= link_to user_path(user) do %>
              <%= attachment_image_tag user, :profile_image, size: "80x80", format: 'jpeg', fallback: "no_image.jpg", class: "rounded-circle" %>
            <% end %>
          </th>
          <td><%= link_to user.name, user_path(user) %></td>
          <td><%= user.introduction%></td>
          <td><%= user.posts.count %></td>
        </tr>
      </tbody>
    <% end %>
</table>
<%= paginate @users %>

app/views/users/edit.html.erb
<div class="container">
  <h2 class="text-center p-3">会員情報編集</h2>
  <div class="row">
    <div class="col-9 offset-3">
      <%= render 'layouts/errors', obj: @user %>
      <%= form_with model: @user, url: user_path(@user), local: true do |f| %>
        <table class="table table-borderless">
          <tbody>
            <tr>
              <td><%= f.label :profile_image, "プロフィール画像" %></td>
              <td><%= f.attachment_field :profile_image %></td>
            </tr>
            <tr>
              <td><%= f.label :neme, "名前" %></td>
              <td><%= f.text_field :name %></td>
            </tr>
            <tr>
              <td><%= f.label :introduction, "プロフィール" %></td>
              <td><%= f.text_area :introduction, :size=>"30x5" %></td>
            </tr>
            <tr>
              <td></td>
              <td><%= f.submit "更新", class: "btn btn-success" %></td>
            </tr>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <h2 class="text-center p-3">会員一覧</h2>
  <%= render "users/index", users: @users %>
</div>

app/views/users/show.html.erb
<div class="container">
  <% if current_user.id == @user.id %>
    <h2 class="text-center p-3">マイページ</h2>
  <% else %>
    <h2 class="text-center p-3"><%= @user.name %>さんのページ</h2>
  <% end %>

  <div class="row mb-4">
    <div class="col-3 offset-1 mt-3">
      <p class="mb-0 ml-4"><%= login_history_image %></p>
      <p><%= attachment_image_tag @user, :profile_image, size: "150x150", format: 'jpeg', fallback: "no_image.jpg", class: "rounded-circle" %></p>
      <p>
        <%= @user.name %>
        <% if @user.id == current_user.id %>
          <%= link_to "", edit_user_path(@user), class: "btn btn-outline-secondary fas fa-user-cog m-2" %>
        <% end %>
      </p>
      <p><%= @user.introduction %></p>
      <% if current_user.id != @user.id %>
        <p id="follow-button">
          <%= render "relationships/follow_button", user: @user %>
        </p>
      <% end %>
      <p id="chat-button">
        <%= render "chats/chat_button", user: @user %>
      </p>
      <table class="row">
      <tr>
        <th>フォロー</th>
        <th>フォロワー</th>
      </tr>
      <tr class="text-center">
        <td id="followings-count"><%= render "relationships/follow_count_following", user: @user %></td>
        <td id="followers-count"><%= render "relationships/follow_count_follower", user: @user %></td>
      </tr>
      </table>
      <% if user_signed_in? && @user == current_user %>
        <%= link_to "退会する", users_withdraw_path, class: "btn btn-sm btn-danger m-3" %>
      <% end %>
    </div>

    <div class="col-7 offset-1">
      <% @posts.each do |post| %>
        <div class="row mt-3">
          <%= attachment_image_tag post, :image,size: "200x200", format: "jpeg", fallback: "post_no_image.jpeg" %>
          <div class="col-6 mt-5">
            <p>
              Title:
              <%= link_to post_path(post) do %>
                <%= post.title %>
              <% end %>
            </p>
            <p><%= post.post_comments.count %>コメント</p>
            <p><%= post.favorites.count %>いいね</p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <%= paginate @posts %>
</div>

app/views/users/withdraw.html.erb
<div class="container">
  <h2 class="text-center p-3">退会画面</h2>
  <div class="text-center">
    <b>本当に退会しますか？</b>
    <p class="mt-3">これまでの投稿等の記録が全て削除されます</p>
    <p>
      <%= link_to '退会しない', user_path(current_user), class: "m-3" %>
      <%= link_to "退会する", user_path(current_user.id), method: :delete, "data-confirm" => "本当に退会しますか？", class: "m-3" %>
    </p>
  </div>
</div>