config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'homes#top'
  get '/about' => 'homes#about', as: 'about'
  post "/homes/guest_sign_in", to: "homes#new_guest"
  resources :posts do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
  end
  get "users/withdraw/:id" => "users#withdraw", as: "users_withdraw"
  resources :chats, only: [:create]
  get "chat/:id" => "chats#show", as: "chat"
  resources :notifications, only: [:index]
end

app/views/layouts/_errors.html.erb
<div class="text-danger">
  <% if obj.errors.any? %>
    <%= obj.errors.count %>件のエラーが発生しました
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li class="list-unstyled"><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class='mt-5 footer'>
    <div class='row'>
      <div class='mx-auto py-3'>
        <p>Copyright © 2021 Yamamoto All Rights Reserved</p>
      </div>
      <p></p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-sm navbar-light header-top-image">
    <div class="container">
      <%= link_to "Make enjoy life", root_path, class: "navbar-brand header-title" %>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <% if user_signed_in? %>
          <ul class="navbar-nav ml-auto">
            <li class="m-3">
              <%= link_to "マイページ", user_path(current_user), class: "btn btn-outline-dark btn-sm" %>
            </li>
            <li class="m-3">
              <% if unchecked_notifications.any? %>
              <i class="fa fa-circle" style="color: #FF00FF;"></i>
            <% end %>
              <%= link_to "通知", notifications_path, class: "btn btn-outline-dark btn-sm" %>
            </li>
            <li class="m-3">
              <%= link_to "会員一覧", users_path, class: "btn btn-outline-dark btn-sm" %>
            </li>
            <li class="m-3">
              <%= link_to '投稿フォーム', new_post_path, class: "btn btn-outline-dark btn-sm" %>
            </li>
            <li class="m-3">
              <%= link_to "投稿一覧", posts_path, class: "btn btn-outline-dark btn-sm" %>
            </li>
            <li class="m-3">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-outline-dark btn-sm" %>
            </li>
          </ul>
        <% else %>
          <ul class="navbar-nav ml-auto">
            <li class="m-3">
              <%= link_to "トップページ", root_path, class: "btn btn-outline-dark btn-sm" %>
            </li>
            <li class="m-3">
              <%= link_to "サイト紹介", about_path, class: "btn btn-outline-dark btn-sm" %>
            </li>
            <li class="m-3">
              <%= link_to "投稿一覧", posts_path, class: "btn btn-outline-dark btn-sm" %>
            </li>
            <li class="m-3">
              <%= link_to "新規登録", new_user_registration_path, class: "btn btn-outline-dark btn-sm" %>
            </li>
            <li class="m-3">
              <%= link_to "ログイン", new_user_session_path, class: "btn btn-outline-dark btn-sm" %>
            </li>
            <li class="m-3">
              <%= link_to "ゲストログイン", homes_guest_sign_in_path, method: :post, class: "btn btn-outline-dark btn-sm" %>
            </li>
          </ul>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Make enjoy life</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Gluten:wght@500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
  </head>

  <body class="body">
    <%= render 'layouts/header' %>
    <main>
      <p id="notice" class="text-center mt-2"><%= notice %></p>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>